name: Windows RDP via Ngrok

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 9999

    steps:
      - name: Download Ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract Ngrok
        run: Expand-Archive ngrok.zip -DestinationPath ngrok

      - name: Connect Ngrok
        run: |
          .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH
        env:
          NGROK_AUTH: ${{ secrets.NGROK_AUTH }}

      - name: Enable RDP & Firewall
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start Ngrok Tunnel
        run: .\ngrok\ngrok.exe tcp 3389
